.TH NETLED 1 "May 1999" \" -*- nroff -*-
.SH NAME
netled \- device monitoring utility
.SH SYNOPSIS
.B netled
<console> <interface> [refresh] [-d] [-k]

.SH DESCRIPTION
.BR netled 
is a device monitoring utility designed to help a system administrator monitor the transmission and recieving of data over a loopback, ppp connection, or ethernet (hell, anything that
.BR ifconfig
can tell you about. 
.BR netled 
was written in C in hopes for an increase in program speed,
efficency, and availability of more options, as opposed to other
shell/perl scripts that are around.  It was designed to ease
the pain of admins who use \'
.BR ifconfig
and
.BR pppstats
to monitor connections.

.SH OPTIONS
.TP
.I "console"
Selects the console you wish to change the LEDs for.  "ttyX" or use "console"
to change the LEDs for all of them.
.br
.I "Example: \'netled tty2 ppp0\'"
.TP
.I "interface"
Select the interface (device) you wish to monitor.  Anything that
.BR ifconfig
can display,
.BR netled
can monitor.  eth0, lo, ppp0, etc.
.br
.I "Example: \'netled console ppp0\'
.TP
.I "refresh"
Set the refresh rate.  The default is 100ms.
.br
.I "Example: \'netled console ppp0 500\'
.TP
.I "\-d"
Deamonize.  Run NetLED as a deamon (without the nasty use of & and skill)
.br
.I "Example: \'netled console ppp0 500 -d\'
.TP
.I "\-k"
Kill.  Kill the running deamon.  You can run NetLED with only this option.
.br
.I "Example: \'netled -k\'

.SH BUGS
It seems that my program will not correctly change the condition
of the keyboard LEDs under some versions/configurations of X.

.SH FIX
If anyone fixes any bugs, or modifies my program in any way, can you please
e-mail me a diff file containing your changes and a description of what they
do? Thanks!

.SH AUTHOR
.TP
Alice Bevan-McGregor <alice@gothcandy.com>

.SH THANKS
Many thanks go out to my friends:
.br
.I Morgan Hughes
for showing me the wonders of Linux
.br
.I RedX
for alpha/beta testing
.br 
.I Midhir
for support and more testing!
.br
.I Steve Shah
&
.I Spoon
for his help with developing a version that works with 2.1.x and 2.2.x
kernels.
.br
.I Robert Lynch
for his time helping me with the blasted RPM system!
.br
.I Gerhard Siegesmund
for everything he did (patches, updates, and more)...
.br
.I Anders
for telling me where I can go to get information on background processing.

.SH FILES
.TP
/etc/netled.conf
